# Generated by Django 5.0.3 on 2024-03-31 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(verbose_name='Дата оформления')),
                ('delivery_date', models.DateTimeField(verbose_name='Дата доставки')),
                ('delivery_id', models.CharField(max_length=100, verbose_name='Номер доставщика')),
                ('car_id', models.CharField(max_length=50, verbose_name='Номер машины')),
                ('description', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название товара')),
                ('product_number', models.CharField(max_length=100, unique=True, verbose_name='Артикул товара')),
                ('price', models.FloatField(verbose_name='Цена товара')),
                ('measurement_unit', models.CharField(max_length=50, verbose_name='Единица измерения')),
                ('is_available_Moscow', models.BooleanField(verbose_name='Доступность в Москве')),
                ('is_available_Saint_Petersburg', models.BooleanField(verbose_name='Доступность в Спб')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Текст вопроса')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('is_done', models.BooleanField(verbose_name='Решен ли вопрос')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Order_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество товара в заказе')),
                ('price', models.FloatField(verbose_name='Цена товара в заказе')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказах',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='api.Order_Products', to='api.product'),
        ),
    ]
